In [2]:
import sqlite3
import logging
from pathlib import Path
from datetime import datetime, timedelta, timezone
from typing import List, Dict
import pandas as pd

In [3]:
db_path = Path.cwd().parent / "data" / "articles.db"
connection = sqlite3.connect(db_path)
query = "SELECT * FROM articles"

df = pd.read_sql_query(query, connection)

connection.close()

df

,id,url,title,content,source_site,scraped_at
0,324,https://towardsdatascience.com/starting-a-care...,Starting a Career in Data Science in the Age o...,Starting a Career in Data Science in the Age o...,towardsdatascience.com,2026-09-18 12:36:34
1,325,https://towardsdatascience.com/multi-agent-cod...,Multi-Agent Coding Isn’t Enough — Agents Need ...,Multi-Agent Coding Isn’t Enough — Agents Need ...,towardsdatascience.com,2026-09-18 12:36:34
2,326,https://towardsdatascience.com/building-a-data...,Building a Data Lakehouse with DuckDB and Duck...,Building a Data Lakehouse with DuckDB and Duck...,towardsdatascience.com,2026-09-18 12:36:34
3,327,https://towardsdatascience.com/how-i-built-a-m...,How I Built a Multi-Agent System for Interrupt...,How I Built a Multi-Agent System for Interrupt...,towardsdatascience.com,2026-09-18 12:36:35
4,328,https://towardsdatascience.com/why-you-think-l...,Why You Think Like a Bayesian but Were Taught ...,Why You Think Like a Bayesian but Were Taught ...,towardsdatascience.com,2026-09-18 12:36:35
...,...,...,...,...,...,...
171,495,https://www.marktechpost.com/2026/09/18/prismm...,PrismML Releases Ternary Bonsai 2 27B: A 5.9 G...,"PrismML has released Ternary Bonsai 2 27B, a t...",marktechpost.com,2026-09-20 05:23:14
172,496,https://www.infoq.com/news/2026/09/lambda-90-m...,AWS Lambda Pushes Serverless Toward Long-Runni...,AWS Lambda now allows functions running on Lam...,infoq.com,2026-09-20 05:23:21
173,497,https://www.infoq.com/news/2026/09/solid-start...,SolidStart 2: Replaces Vinxi with a Vite 8 and...,"SolidStart, the full-stack meta-framework buil...",infoq.com,2026-09-20 05:23:21
174,498,https://www.infoq.com/news/2026/09/mariadb-13-...,MariaDB 13 Expands Oracle Compatibility and Im...,MariaDB Community Server 13.0 has reached Gene...,infoq.com,2026-09-20 05:23:22
175,499,https://www.infoq.com/news/2026/09/doordash-fe...,"DoorDash Uses Multi Agent LLMs to Clean up 60,...",DoorDash has built a multi-agent LLM system to...,infoq.com,2026-09-20 05:23:22

In [4]:
db_path = Path.cwd().parent / "data" / "articles.db"
connection = sqlite3.connect(db_path)
query_2 = "SELECT COUNT() as Number_of_articles FROM articles"

df = pd.read_sql_query(query_2, connection)

connection.close()

df

   Number_of_articles
0                 176

In [8]:
db_path_3 = Path.cwd().parent / "data" / "articles.db"
connection = sqlite3.connect(db_path_3)

query_3 = "SELECT COUNT(source_site) as Number_of_articles, source_site as Name_of_site FROM articles GROUP BY source_site"

df = pd.read_sql_query(query_3, connection)

connection.close()

df

    Number_of_articles                     Name_of_site
0                    1                      abcnews.com
1                   10              analyticsvidhya.com
2                   10  artificialintelligence-news.com
3                   10             blog.research.google
4                    1             blog.trailofbits.com
5                   10                 blogs.nvidia.com
6                    1                     computer.org
7                   10                  deepmind.google
8                    1                  goto10retro.com
9                   14                        infoq.com
10                   1                          jawz.ai
11                  10                    kdnuggets.com
12                  11       machinelearningmastery.com
13                  18                 marktechpost.com
14                   1         mhclgdigital.blog.gov.uk
15                   1                          msn.com
16                  10                pub.towardsai.net
17                   2                       reddit.com
18                  20                   techcrunch.com
19                  10             technologyreview.com
20                   1                     theverge.com
21                  14           towardsdatascience.com
22                   1                      twitter.com
23                   7                  venturebeat.com
24                   1                     waterfox.com

In [ ]:
db_path_4 = Path.cwd().parent / "data" / "articles.db"
connection = sqlite3.connect(db_path_4)

query_4 = ("SELECT * FROM articles WHERE source_site IN (SELECT source_site FROM articles GROUP BY source_site HAVING COUNT(source_site) = 1)")

df = pd.read_sql_query(query_4, connection)

connection.close()

DatabaseError: Execution failed on sql 'SELECT * FROM articles WHERE source_site IN (SELECT source_site FROM articles GROUP BY source_site HAVING COUNT(source_site) = 1': incomplete input