In [1]:
import sqlite3
import logging
from pathlib import Path
from datetime import datetime, timedelta, timezone
from typing import List, Dict
import pandas as pd

In [10]:
db_path = Path.cwd().parent / "data" / "articles.db"
connection = sqlite3.connect(db_path)
query = "SELECT * FROM articles"

df = pd.read_sql_query(query, connection)

connection.close()

df

,id,url,title,content,source_site,scraped_at
0,182,https://towardsdatascience.com/10-statistical-...,10 Statistical Traps We Often Overlook,10 Statistical Traps We Often Overlook\nStatis...,towardsdatascience.com,2026-09-09 12:12:27
1,183,https://towardsdatascience.com/how-to-maximize...,How to Maximize GPT-6 Astra,How to Maximize GPT-6 Astra\nMy first impressi...,towardsdatascience.com,2026-09-09 12:12:27
2,184,https://towardsdatascience.com/the-model-valid...,The Model Validation Playbook for GenAI: Lesso...,The Model Validation Playbook for GenAI: Lesso...,towardsdatascience.com,2026-09-09 12:12:27
3,185,https://towardsdatascience.com/a-beginners-gui...,A Beginner’s Guide to World Models,A Beginner’s Guide to World Models\nLearn how ...,towardsdatascience.com,2026-09-09 12:12:27
4,186,https://towardsdatascience.com/introducing-shi...,Introducing ShipAI,Introducing ShipAI\nTowards Data Science launc...,towardsdatascience.com,2026-09-09 12:12:27
...,...,...,...,...,...,...
137,319,https://deepmind.google/blog/gemini-omni-1-1-f...,Gemini Omni 1.1 Flash lets you build with more...,Gemini Omni 1.1 Flash lets you build with more...,deepmind.google,2026-09-09 12:17:12
138,320,https://deepmind.google/blog/piloting-the-worl...,Piloting the world's first double-blind AI eva...,Piloting the world's first double-blind AI eva...,deepmind.google,2026-09-09 12:17:13
139,321,https://deepmind.google/blog/intelligent-trans...,Intelligent transcription with Gemini 3.5 Tran...,Intelligent transcription with Gemini 3.5 Tran...,deepmind.google,2026-09-09 12:17:13
140,322,https://deepmind.google/blog/from-atari-to-eve...,From Atari to EVE Online: Building on 15 Years...,From Atari to EVE Online: Building on 15 Years...,deepmind.google,2026-09-09 12:17:13
141,323,https://deepmind.google/blog/introducing-gemin...,Introducing Gemini 3.7 Flash,"Introducing Gemini 3.7 Flash\nToday, we’re bui...",deepmind.google,2026-09-09 12:17:14

In [11]:
db_path = Path.cwd().parent / "data" / "articles.db"
connection = sqlite3.connect(db_path)
query_2 = "SELECT COUNT() as Number_of_articles FROM articles"

df = pd.read_sql_query(query_2, connection)

connection.close()

df

   Number_of_articles
0                 142