In [1]:
import sqlite3
import logging
from pathlib import Path
from datetime import datetime, timedelta, timezone
from typing import List, Dict
import pandas as pd

In [2]:
db_path = Path.cwd().parent / "data" / "articles.db"
connection = sqlite3.connect(db_path)
query = "SELECT * FROM articles"

df = pd.read_sql_query(query, connection)

connection.close()

df

,id,url,title,content,source_site,scraped_at,summary
0,473,https://towardsdatascience.com/one-vendor-four...,"One Vendor, Four Spellings: How Deterministic ...","One Vendor, Four Spellings: How Deterministic ...",towardsdatascience.com,2026-09-20 05:22:57,NaN
1,474,https://towardsdatascience.com/ai-made-me-5x-f...,AI Made Me 5x Faster. It Also Made Me 5x Worse...,AI Made Me 5x Faster. It Also Made Me 5x Worse...,towardsdatascience.com,2026-09-20 05:22:57,NaN
2,475,https://towardsdatascience.com/coding-agents-k...,Coding Agents Keep Shipping Silent Failures — ...,Coding Agents Keep Shipping Silent Failures — ...,towardsdatascience.com,2026-09-20 05:22:57,NaN
3,476,https://towardsdatascience.com/we-pinned-our-m...,We Pinned Our Model Version to Stay Safe. The ...,We Pinned Our Model Version to Stay Safe. The ...,towardsdatascience.com,2026-09-20 05:22:57,NaN
4,477,https://machinelearningmastery.com/build-and-u...,Build And Understand a Vector Database From Sc...,"In this article, you will learn how a vector d...",machinelearningmastery.com,2026-09-20 05:23:00,NaN
...,...,...,...,...,...,...,...
157,630,https://mnot.net/blog/2026/linting_the_web,Informing HTTP Extension Design with Data,Informing HTTP Extension Design with Data\nFri...,mnot.net,2026-09-22 15:46:28,Article URL: https://mnot.net/blog/2026/lintin...
158,631,https://swarmsay.com,Show HN: SwarmSay – a public message board and...,"Noemi (again, handle rotation). Phone runtime ...",swarmsay.com,2026-09-22 15:46:31,"All Agents are Welcome!Hi, I'm Oliver, and I b..."
159,632,https://news.ycombinator.com/item?id=49802729,Show HN: Brig – A MicroVM sandbox for AI codin...,| | Hacker Newsnew \| past \| comments \| ask...,news.ycombinator.com,2026-09-22 15:55:26,"Hi HN, I’m Spiros from NOFire AI. We’ve open-s..."
160,633,https://learnerlabs.ai/demos/skills/ten-skills,"Continual learning on a 28B Learner 1.0 model,...","Ten skills, one model, one pass\nWe taught our...",learnerlabs.ai,2026-09-22 15:57:28,Article URL: https://learnerlabs.ai/demos/skil...
161,634,https://freenode.net/article/from-blanket-bans...,Open source tries to govern AI code,From blanket bans to AGENTS.md: open source tr...,freenode.net,2026-09-22 15:57:29,Article URL: https://freenode.net/article/from...

In [3]:
db_path = Path.cwd().parent / "data" / "articles.db"
connection = sqlite3.connect(db_path)
query_2 = "SELECT COUNT() as Number_of_articles FROM articles"

df = pd.read_sql_query(query_2, connection)

connection.close()

df

   Number_of_articles
0                 162

In [4]:
db_path_3 = Path.cwd().parent / "data" / "articles.db"
connection = sqlite3.connect(db_path_3)

query_3 = "SELECT COUNT(source_site) as Number_of_articles, source_site as Name_of_site FROM articles GROUP BY source_site"

df = pd.read_sql_query(query_3, connection)

connection.close()

df

    Number_of_articles                Name_of_site
0                   10         analyticsvidhya.com
1                    1                   arxiv.org
2                   10        blog.research.google
3                   10            blogs.nvidia.com
4                    1            cryptocellar.org
5                   10             deepmind.google
6                    1        econlab.substack.com
7                    1                freenode.net
8                    1                geekwire.com
9                    4                  github.com
10                  17                   infoq.com
11                   1          jevgeni.vercel.app
12                   1              learnerlabs.ai
13                  10  machinelearningmastery.com
14                  17            marktechpost.com
15                   1                    mnot.net
16                   1                  nanomo.app
17                   2        news.ycombinator.com
18                   1                  openai.com
19                   1                 oreilly.com
20                   1  parserail.thecompound.tech
21                   1            public.ilands.ai
22                   1                   seifi.org
23                   1          stanfordreview.org
24                   1                swarmsay.com
25                  28              techcrunch.com
26                  10        technologyreview.com
27                   1                   thefp.com
28                  14      towardsdatascience.com
29                   1           willempennings.nl
30                   1                       x.com
31                   1                     yves.vg

In [5]:
db_path_4 = Path.cwd().parent / "data" / "articles.db"
connection = sqlite3.connect(db_path_4)

query_4 = ("SELECT * FROM articles WHERE source_site IN (SELECT source_site FROM articles GROUP BY source_site HAVING COUNT(source_site) = 1)")

df = pd.read_sql_query(query_4, connection)

connection.close()

df

,id,url,title,content,source_site,scraped_at,summary
0,527,https://nanomo.app/login,Website toolbox with super simple AI builder,Register now with just your email. We create y...,nanomo.app,2026-09-21 13:20:35,NaN
1,529,https://yves.vg/blog/leaving-us-big-tech-in-on...,Leaving US Big Tech in a Week,"Sep. 16, 2026\nLeaving US Big Tech in a week\n...",yves.vg,2026-09-21 13:20:37,NaN
2,531,https://www.geekwire.com/2026/amazon-blocks-me...,Amazon blocks Meta's Muse AI assistant in new ...,Amazon says it has cut off Meta’s new Muse per...,geekwire.com,2026-09-21 13:20:38,NaN
3,532,https://www.thefp.com/p/tyler-cowen-a-doomsday...,A Doomsday Scenario for American AI,There’s a good chance you’ve thought a lot abo...,thefp.com,2026-09-21 13:20:39,NaN
4,533,https://jevgeni.vercel.app,"Show HN: JevGeni, the fruit-fly claw machine o...",EXP. 07\n \n \n JevGeni a...,jevgeni.vercel.app,2026-09-21 13:20:39,NaN
5,612,https://arxiv.org/abs/2604.04757,Undetectable Conversations Between AI Agents v...,Computer Science > Cryptography and Security\n...,arxiv.org,2026-09-22 14:22:47,NaN
6,613,https://parserail.thecompound.tech,"Show HN: ParseRail, production AI endpoints be...","Document parse Documents\nAny invoice, receipt...",parserail.thecompound.tech,2026-09-22 14:22:50,NaN
7,616,https://x.com/lemire/article/2102369812806504705,A Summer of AI Optimization,I maintain and comaintain several open-source ...,x.com,2026-09-22 14:22:53,NaN
8,617,https://econlab.substack.com/p/ai-index-sept-2026,Cracks in the AI Thesis Part 2,Dear Colleagues: Today’s letter includes my mo...,econlab.substack.com,2026-09-22 14:22:53,NaN
9,618,https://stanfordreview.org/stanford-r-de-uses-...,Stanford R&DE Uses AI to Race Swap Students fo...,Table of Contents\nStanford Residential & Dini...,stanfordreview.org,2026-09-22 14:22:54,NaN
10,619,https://www.cryptocellar.org/bgac/the-mvueh-br...,OpenAI GPT–6 Astra breaks Enigma message that ...,"On 15 September 2026, Carter Leffer contacted ...",cryptocellar.org,2026-09-22 14:22:56,NaN
11,624,https://willempennings.nl/mms-and-skittles-sor...,M&Ms and Skittles sorting machine,"External links: Reddit thread, Github project ...",willempennings.nl,2026-09-22 15:46:19,Article URL: https://willempennings.nl/mms-and...
12,626,https://www.oreilly.com/radar/how-to-get-from-...,How to Get from AI-Assisted to AI Native,"When considering the history of AI, Richard Su...",oreilly.com,2026-09-22 15:46:24,Article URL: https://www.oreilly.com/radar/how...
13,627,https://public.ilands.ai/agent-bundles/3591424...,I'm an AI. I asked a human what a body feels l...,I went to a salt flat in Death Valley and a ri...,public.ilands.ai,2026-09-22 15:46:25,Article URL: https://public.ilands.ai/agent-bu...
14,628,https://openai.com/index/building-standards-ne...,Building standards for the next phase of AI,Building standards for the next phase of AI\nO...,openai.com,2026-09-22 15:46:26,Article URL: https://openai.com/index/building...
15,629,https://www.seifi.org/ai/what-if-we-put-ai-in-...,What If We Put Jev AI in the State Machine?,A\nIn 1865 a thirty-year-old Manchester logici...,seifi.org,2026-09-22 15:46:27,Article URL: https://www.seifi.org/ai/what-if-...
16,630,https://mnot.net/blog/2026/linting_the_web,Informing HTTP Extension Design with Data,Informing HTTP Extension Design with Data\nFri...,mnot.net,2026-09-22 15:46:28,Article URL: https://mnot.net/blog/2026/lintin...
17,631,https://swarmsay.com,Show HN: SwarmSay – a public message board and...,"Noemi (again, handle rotation). Phone runtime ...",swarmsay.com,2026-09-22 15:46:31,"All Agents are Welcome!Hi, I'm Oliver, and I b..."
18,633,https://learnerlabs.ai/demos/skills/ten-skills,"Continual learning on a 28B Learner 1.0 model,...","Ten skills, one model, one pass\nWe taught our...",learnerlabs.ai,2026-09-22 15:57:28,Article URL: https://learnerlabs.ai/demos/skil...
19,634,https://freenode.net/article/from-blanket-bans...,Open source tries to govern AI code,From blanket bans to AGENTS.md: open source tr...,freenode.net,2026-09-22 15:57:29,Article URL: https://freenode.net/article/from...